language: node_js
node_js:
  - 0.10

before_install:
  - npm install -g bower
  - npm install grunt-build-control --save-dev
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# whitelist
branches:
  only:
    - master

after_success:
  - grunt buildcontrol
