language: node_js
node_js:
  - 0.10

before_install:
  - npm install -g bower
  - npm install -g grunt-build-control
  - npm install -g grunt-cli
  - npm install -g grunt
  - npm install -g grunt-contrib-compass
  - gem install compass
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# whitelist
branches:
  only:
    - master

after_success:
  - grunt deploy
