language: node_js
node_js:
  - 0.10

before_install:
  - npm install -g bower
  - npm install grunt-build-control --save-dev
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# whitelist
branches:
  only:
    - master

after_success:
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy git@github.com:nicolae-olariu/travis-test-2.git
  - git push deploy
